import './globals.css';

import type { Metadata } from 'next';
import { Geist, Plus_Jakarta_Sans } from 'next/font/google';
import { Providers } from '@/components/providers/providers';
import { ScrollArea } from '@/components/ui/scroll-area';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'WealthWise',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en' className='scroll-smooth' suppressHydrationWarning>
      <body className={`${geistSans.className} antialiased`} suppressHydrationWarning>
        <Providers>
          <ScrollArea className='h-screen'>{children}</ScrollArea>
        </Providers>
      </body>
    </html>
  );
}
